apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        resources:
          limits:
            memory: "300Mi"
            cpu: "200m"
        ports:
        - name : ftps
          containerPort: 21
          hostPort : 21

---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations: 
    metallb.universe.tf/allow-shared-ip : shared-ip
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - protocol: TCP
      name: http
      port: 21
      targetPort: 21