apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        imagePullPolicy: Never
        resources:
          limits:
            memory: "200Mi"
            cpu: "100m"
        ports:
        - name : phpmyadmin
          containerPort: 5000
          hostPort : 5000


