apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        resources:
          limits:
            memory: "200Mi"
            cpu: "100m"
        ports:
        - name : wordpress
          containerPort: 5050
          hostPort : 5050
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations: 
    metallb.universe.tf/allow-shared-ip : shared-ip
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      name: wordpress
      port: 5050
      targetPort: 5050
    

