apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        resources:
          limits:
            memory: "200Mi"
            cpu: "100m"
        ports:
        - name : wordpress
          containerPort: 5050
          hostPort : 5050


